I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/script.rpy", line 37, in script call
    call chapter1
  File "game/script/chapter1.rpy", line 6, in script
    n "Когда поезд наконец остановился,"
Exception: Sayer 'n' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/script.rpy", line 37, in script call
    call chapter1
  File "game/script/chapter1.rpy", line 6, in script
    n "Когда поезд наконец остановился,"
  File "C:\Users\User\Desktop\renpy-8.0.1-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\User\Desktop\renpy-8.0.1-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'n' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.1.22070801
There is no god in Hinterland 1.0
Tue Sep  6 15:22:31 2022
